const OverviewActionTypes = {
    GET_CURRENT_POSITION: 'GET_CURRENT_POSITION',
    DISPLAY_WEATHER: 'DISPLAY_WEATHER',
    FETCH_DATA_START: 'FETCH_DATA_START',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE'
}

export default OverviewActionTypes