export const TemperatureActionTypes = {
    FETCH_TEMPERATURE_DATA_START: 'FETCH_TEMPERATURE_DATA_START',
    FETCH_TEMPERATURE_DATA_SUCCESS: 'FETCH_TEMPERATURE_DATA_SUCCESS',
    FETCH_TEMPERATURE_DATA_FAILURE: 'FETCH_TEMPERATURE_DATA_FAILURE',
    CLEAR_TEMPERATURE_DATA: 'CLEAR_TEMPERATURE_DATA'

}